-- Pizza Sales Case Study – Project Questions

-------------- BUSINESS UNDERSTANDING --------------------
-- What is the total revenue generated by the pizza store?

use pizzahut;

SELECT SUM(order_details.quantity * pizza.price) AS total_revenue
FROM order_details
JOIN pizza ON order_details.pizza_id = pizza.pizza_id;

-- What is the total number of orders placed?

SELECT COUNT(DISTINCT order_id) AS total_orders
FROM orders;

-- What is the average order value (AOV)?

SELECT SUM(order_details.quantity * pizza.price) / COUNT(DISTINCT order_details.order_id) AS avg_order_value
FROM order_details
JOIN pizza ON order_details.pizza_id = pizza.pizza_id;

-- How many pizzas are sold per day on average?

SELECT AVG(daily_quantity) AS avg_pizzas_per_day
FROM (SELECT orders.order_date,
	SUM(order_details.quantity) AS daily_quantity
  FROM orders JOIN order_details ON orders.order_id = order_details.order_id
  GROUP BY orders.order_date
) daily;

--------------- SALES PERFORMANCE ANALYSIS ------------------

-- Which pizza type generates the highest revenue?
-- “The Classic Deluxe Pizza” is the top by revenue --

SELECT pizza_types.name AS pizza_type,
    SUM(order_details.quantity * pizza.price) AS total_revenue
FROM order_details 
JOIN pizza ON order_details.pizza_id = pizza.pizza_id
JOIN pizza_types ON pizza.pizza_type_id = pizza_types.pizza_type_id
GROUP BY pizza_types.name
ORDER BY total_revenue DESC;

-- Which pizza size (S, M, L, XL) sells the most
-- Size L (Large) sells the most in terms of quantity.

SELECT pizza.size,
    SUM(order_details.quantity) AS total_sold
FROM order_details JOIN pizza ON order_details.pizza_id = pizza.pizza_id
GROUP BY pizza.size
ORDER BY total_sold DESC;

-- 5 most ordered pizza types along with their quanities

select pizza_types.name as pizza_name,
sum(order_details.quantity) as total_quantity_sold from order_details
JOIN pizza ON order_details.pizza_id = pizza.pizza_id
JOIN pizza_types ON pizza.pizza_type_id = pizza_types.pizza_type_id
group by pizza_types.name
order by total_quantity_sold desc limit 5;

-- Bottom 5 least-selling pizzas

SELECT pizza_types.name AS pizza_name,
    SUM(order_details.quantity) AS total_quantity_sold FROM order_details
JOIN pizza ON order_details.pizza_id = pizza.pizza_id
JOIN pizza_types on pizza.pizza_type_id = pizza_types.pizza_type_id
GROUP BY pizza_types.name
ORDER BY total_quantity_sold ASC LIMIT 5;

-- Which pizza category performs best in terms of revenue

SELECT pizza_types.category,
    SUM(order_details.quantity * pizza.price) AS total_revenue
FROM order_details
JOIN pizza ON order_details.pizza_id = pizza.pizza_id
JOIN pizza_types ON pizza.pizza_type_id = pizza_types.pizza_type_id
GROUP BY pizza_types.category
ORDER BY total_revenue DESC;

---------------- TIME BASED ANALYSIS--------------

-- Which hour of the day has the highest number of orders?

SELECT 
    HOUR(order_time) AS order_hour,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_hour
ORDER BY total_orders DESC
LIMIT 1;

-- On which day of the week are sales highest?

SELECT 
    DAYNAME(order_date) AS day_name,
    SUM(order_details.quantity * pizza.price) AS total_sales
FROM orders
JOIN order_details ON orders.order_id = order_details.order_id
JOIN pizza ON order_details.pizza_id = pizza.pizza_id
GROUP BY day_name
ORDER BY total_sales DESC;

-- What is the monthly sales trend?

SELECT 
    MONTHNAME(o.order_date) AS month,
    SUM(od.quantity * p.price) AS monthly_revenue
FROM orders o
JOIN order_details od ON o.order_id = od.order_id
JOIN pizza p ON od.pizza_id = p.pizza_id
GROUP BY MONTH(o.order_date), MONTHNAME(o.order_date)
ORDER BY MONTH(o.order_date);

-- Identify peak and non-peak sales periods (by hour)

SELECT 
    HOUR(order_time) AS order_hour,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_hour
ORDER BY total_orders DESC;

------------------------- CUSTOMER ORDER BEHAVIOUR------------------------------

-- What is the average number of pizzas per order?

SELECT ROUND(AVG(pizzas_per_order), 2) AS avg_pizzas_per_order
FROM (SELECT order_id, SUM(quantity) AS pizzas_per_order
FROM order_details
GROUP BY order_id) AS order_summary;

-- What is the most common combination of pizzas ordered together?

SELECT o.order_id,
GROUP_CONCAT(pt.name ORDER BY pt.name SEPARATOR ', ') AS pizza_combination,
COUNT(*) AS frequency
FROM orders o
JOIN order_details od ON o.order_id = od.order_id
JOIN pizza p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY o.order_id
ORDER BY frequency DESC
LIMIT 5;

------------------ ADVANCED CASE STUDY------------
-- Find top 3 pizzas by revenue

SELECT p.pizza_id, pt.name, SUM(od.quantity * p.price) AS revenue  
FROM order_details od  
JOIN pizza p ON od.pizza_id = p.pizza_id  
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id  
GROUP BY p.pizza_id, pt.name  
ORDER BY revenue DESC  
LIMIT 3;

-- Calculate running total of daily sales

SELECT order_date,  
       SUM(daily_sales) OVER (ORDER BY order_date) AS running_total  
FROM (  
  SELECT o.order_date, SUM(od.quantity * p.price) AS daily_sales  
  FROM orders o  
  JOIN order_details od ON o.order_id = od.order_id  
  JOIN pizza p ON od.pizza_id = p.pizza_id  
  GROUP BY o.order_date  
) t;


-- Rank pizzas based on total revenue

SELECT pt.name,  
       SUM(od.quantity * p.price) AS revenue,  
       RANK() OVER (ORDER BY SUM(od.quantity * p.price) DESC) AS revenue_rank  
FROM order_details od  
JOIN pizza p ON od.pizza_id = p.pizza_id  
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id  
GROUP BY pt.name;


-- Find category-wise revenue using JOIN & GROUP BY

SELECT pt.category,  
       SUM(od.quantity * p.price) AS revenue  
FROM order_details od  
JOIN pizza p ON od.pizza_id = p.pizza_id  
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id  
GROUP BY pt.category;


-- Create a view for monthly sales report

CREATE VIEW monthly_sales AS  
SELECT DATE_TRUNC('month', o.order_date) AS month,  
       SUM(od.quantity * p.price) AS monthly_sales  
FROM orders o  
JOIN order_details od ON o.order_id = od.order_id  
JOIN pizza p ON od.pizza_id = p.pizza_id  
GROUP BY DATE_TRUNC('month', o.order_date)  
ORDER BY month;

(
 SELECT orders.order_date,
        SUM(order_details.quantity) AS daily_quantity
 FROM orders
 JOIN order_details ON orders.order_id = order_details.order_id
 GROUP BY orders.order_date
)